server {
    listen 3000;
    root /usr/share/nginx/html;
    index index.html;

    client_header_buffer_size 16k;
    large_client_header_buffers 4 16k;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
